language: python

matrix:
  include:
    - os: linux
      python: "3.6"
      env: flake8=true
    - os: linux
      python: "3.6"
      env: doc=true
    - os: linux
      python: "2.7"
      env: PYTHON=2
    - os: linux
      python: "3.6"
      env: PYTHON=3
    - os: osx
      language: generic
      env: PYTHON=2
    - os: osx
      language: generic
      env: PYTHON=3

addons:
  apt:
    packages:
    - graphviz


# Perform the manual steps on osx to install python3 and activate venv
before_install:

    - eval key=\$encrypted_${SSH_KEY_TRAVIS_ID}_key
    - eval iv=\$encrypted_${SSH_KEY_TRAVIS_ID}_iv
    - |
       if [ "$TRAVIS_OS_NAME" = "osx" ]; then
         brew update
         if [ "$PYTHON" = "2" ]; then
           brew install python@2
           export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
         else
           brew upgrade python  # upgrade to Python 3
           export PATH="/usr/local/opt/python/libexec/bin:$PATH"
         fi
       fi

install:
  - pip install -U pytest mock six flake8 pyyaml codecov pytest-cov
  - if [ "$PYTHON" = "3" ]; then pip install -U pytest-asyncio; fi
  - if [ "$doc" = true ]; then pip install -U sphinx sphinx-argparse pygraphviz; fi

script:
  - python --version
  - if [ "$PYTHON" = "2" ]; then python setup.py build_ext --inplace; fi
  - PYTHONPATH=`pwd`/src python -m faber.platform
  - |
     if [ "$flake8" = true ]; then
       flake8 src/faber tests scripts/faber
     elif [ "$doc" = true ]; then
       PYTHONPATH=`pwd`/src scripts/faber --srcdir=doc --builddir=build
       .ci/upload_docs.sh
     else
       PYTHONPATH=`pwd`/src scripts/faber --info=tools cxx
       PYTHONPATH=`pwd`/src py.test --cov=./src --compiler=native -v
     fi

after_success:
  - codecov
