name: Test Windows

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: prerequisites
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-asyncio mock flake8 pyyaml codecov pytest-cov
    - name: lint
      run: |
        flake8 src/faber tests
    - name: test
      shell: cmd
      run: |
        set PYTHONPATH=%cd%\\src
        python -m faber.cli --info=tools cxx
        pytest --cov=./src --compiler=native -vs
    - name: coverage
      run: |
        codecov
